// 登录
export const RECEIVE_LOGININFO = 'RECEIVE_LOGININFO'
export const CHECKOUT_LOGINMSG = 'CHECKOUT_LOGINMSG'

// 前端笔记
export const RECEIVE_NOTES = 'RECEIVE_NOTES'
export const RECEIVE_NOTEDETAIL = 'RECEIVE_NOTEDETAIL'
